cd /home/ubuntu/Target
nohup python recommendParallel.py 10 &
nohup python recommendParallel.py 11 &
nohup python recommendParallel.py 12 &
nohup python recommendParallel.py 13 &
nohup python recommendParallel.py 14 &
nohup python recommendParallel.py 15 &
nohup python recommendParallel.py 16 &
nohup python recommendParallel.py 17 &
nohup python recommendParallel.py 18 &
nohup python recommendParallel.py 19 &
nohup python recommendParallel.py 20 &
nohup python recommendParallel.py 21 &
nohup python recommendParallel.py 22 &
nohup python recommendParallel.py 23 &
nohup python recommendParallel.py 24 &
nohup python recommendParallel.py 25 &
nohup python recommendParallel.py 26 &
nohup python recommendParallel.py 27 &
nohup python recommendParallel.py 28 &
nohup python recommendParallel.py 29 &
nohup python recommendParallel.py 30 &
nohup python recommendParallel.py 31 &
nohup python recommendParallel.py 32 &
nohup python recommendParallel.py 33 &
nohup python recommendParallel.py 34 &
nohup python recommendParallel.py 35 &
nohup python recommendParallel.py 36 &
nohup python recommendParallel.py 37 &
nohup python recommendParallel.py 38 &
nohup python recommendParallel.py 39 &
nohup python recommendParallel.py 40 &
nohup python recommendParallel.py 41 &
nohup python recommendParallel.py 42 &
nohup python recommendParallel.py 43 &
nohup python recommendParallel.py 44 &
nohup python recommendParallel.py 45 &
nohup python recommendParallel.py 46 &
nohup python recommendParallel.py 47 &
nohup python recommendParallel.py 48 &
nohup python recommendParallel.py 49 &
